# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77ff720d6d973d6d5db67e1e38db412d1b90c8ec8a361fe099cd644f1f871473d693f9fe6e8b86f85c8a886f32329e55a0223facd2bf8ef27cf50a16bc5e71f0

test:
  secret_key_base: d56c24e04af34222071185cb7d570c61870692145680c472b540320c08f2b470ab8bde3d317d5bd971624892e42b973de67dc86f50706574ac2864b9f245c480

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
